baseURL = "https://hortluck.com/"
languageCode = "tr-tr"
title = "Tıp Notları"
theme = "PaperMod"

[pagination]
  pagerSize = 10

enableRobotsTXT = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML", "Reveal"]

[params]
  env = "production"
  title = "Tıp Notları"
  description = "Dahiliye kişisel not arşivi"
  defaultTheme = "auto"
  disableThemeToggle = false

  showReadingTime = false
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Tıp Notları"
    Content = "Diyabet, oral antidiyabetikler, HT, dislipidemi hızlı bakış notları."


# Menü
[menu]

  [[menu.main]]
    name = "Diyabet (Slayt)"
    url = "/diyabet/"
    weight = 10

  [[menu.main]]
    name = "Oral AD (Kart)"
    url = "/oral-antidiyabetikler/"
    weight = 20

[outputFormats.Reveal]
  name = "Reveal"
  mediaType = "text/html"
  baseName = "index"
  isHTML = true
  noUgly = true
